# Loading data and clean it

To make import module in python available

In [12]:
import sys
from pathlib import Path

sys.path.append(str(Path("../").resolve()))

In [13]:
from src.preprocess import clean_dataframe, clean_text

In [ ]:
import pandas as pd

In [26]:
df = pd.read_csv("/Users/ahmadabotrab/Desktop/arabic_sentiment_classification/data/Arabic_tweets_sentiment.csv",sep="\t")

In [27]:
df.head()

,Unnamed: 0,text,class,id
0,0,انت فارقني انا تمام الشعب الاردني شعبي وجزء من...,Negative,"""1715110556502278180"""
1,1,انت ماقابلته الاردن رحت مقابلو مصر عار عليكم,Negative,"""1715110520997531953"""
2,2,بعد طلبه فتح الحدود ومحاربة الاسرائيليين ممثل ...,Neutral,"""1715110511140798562"""
3,3,وناااسه راح تصير اعماركم؟ ستشاهده خبر عظيم جد...,Neutral,"""1715110486071472585"""
4,4,ممثل شهير يكشف مأساة عائلة زوجته غزة عمليهطوفا...,Negative,"""1715110436088021404"""

In [28]:
print(df.shape)
print(df.columns.tolist())
print(df.isnull().sum())

(2286128, 4)
['Unnamed: 0', 'text', 'class', 'id']
Unnamed: 0       0
text          5612
class            0
id               0
dtype: int64

In [29]:
TEXT_COL = "text"
LABEL_COL = "class"

In [30]:
cleaned_df = clean_dataframe(df, text_col=TEXT_COL, label_col=LABEL_COL)
cleaned_df.head()

                                                text     label
0  انت فارقني انا تمام الشعب الاردني شعبي وجزء من...  Negative
1       انت ماقابلته الاردن رحت مقابلو مصر عار عليكم  Negative
2  بعد طلبه فتح الحدود ومحاربه الاسراييليين ممثل ...   Neutral
3  وناااسه راح تصير اعماركم؟ ستشاهده خبر عظيم جدا...   Neutral
4  ممثل شهير يكشف ماساه عايله زوجته غزه عمليهطوفا...  Negative

In [31]:
print("Original shape:", df.shape)
print("Cleaned shape:", cleaned_df.shape)
print(cleaned_df["label"].value_counts())

Original shape: (2286128, 4)
Cleaned shape: (1177415, 2)
label
Negative    627138
Neutral     309069
Positive    241208
Name: count, dtype: int64

In [32]:
raw_samples = df[[TEXT_COL, LABEL_COL]].dropna().head(5)

for _, row in raw_samples.iterrows():
    raw_text = str(row[TEXT_COL])
    cleaned_text = clean_text(raw_text)
    print("RAW    :", raw_text)
    print("CLEANED:", cleaned_text)
    print("-" * 80)

RAW    : انت فارقني انا تمام الشعب الاردني شعبي وجزء مني وانا جزء منو انت وامثالك اعداء للوحدة العربية وعملاء للاستعمار هلق اعرفت مين يحارب شعبي الاردن ويقمعو منشان نتنياهو
CLEANED: انت فارقني انا تمام الشعب الاردني شعبي وجزء مني وانا جزء منو انت وامثالك اعداء للوحده العربيه وعملاء للاستعمار هلق اعرفت مين يحارب شعبي الاردن ويقمعو منشان نتنياهو
--------------------------------------------------------------------------------
RAW    : انت ماقابلته الاردن رحت مقابلو مصر عار عليكم
CLEANED: انت ماقابلته الاردن رحت مقابلو مصر عار عليكم
--------------------------------------------------------------------------------
RAW    : بعد طلبه فتح الحدود ومحاربة الاسرائيليين ممثل شهير يكشف تلقيه رسالة تهديد عمليهطوفانالاقصي كتايبالقسام طوفانالاقصي طوفانالقدس الاردن الاردن
CLEANED: بعد طلبه فتح الحدود ومحاربه الاسراييليين ممثل شهير يكشف تلقيه رساله تهديد عمليهطوفانالاقصي كتايبالقسام طوفانالاقصي طوفانالقدس الاردن الاردن
--------------------------------------------------------------------------------
RAW    : وناااسه راح تصير اعماركم؟  ستشاهده خبر عظيم جداً وتفاصيل الحلم الذي سيصبح حقيقة بإذن الله كاس العالم السعودية  المملكة العربية السعودية تحصل على دعم دولة وإتحاد دولي لإستضافة كاس العالم  الدول الداعمة للمملكة الاردن قطر البحرين الامارات الكويت سلطنة عمان العراق لبنان فلسطين سوريا اليمن ايران افغانستان باكستان اوزباكستان قيرغيزستان تركمانستان طاجكستان كوريا الجنوبية كوريا الشمالية اليابان الصين تايبيه الصينية غوام هونغ كونغ ماكاو منغوليا جزر مارينا الشمالية استراليا بروناي كمبوديا تيمور الشرقية اندونيسيا لاوس ماليزيا ميانمار الفلبين سنغافورة تايلاند فيتنام بنغلادش بوتان سريلانكا المالديف نيبال تونس مصر المغرب الجزائر ليبيا السودان جيبوتي الصومال جزر القمر موريتانيا بنين بوركينا فاسو توغو الراس الاخضر غينيا ساحل العاج تنزانيا السنغال سيراليون غامبيا غانا غينيا بيساو ليبيريا مالي نيجيريا النيجر افريقيا الوسطى تشاد ساو تاومي وبرينسيب الغابون غينيا الاستوائية الكاميرون الكونغو الكونغو الديموقراطية اثيوبيا اريتريا اوغندا بوروندي جنوب السودان رواندا زنجبار كينيا اسواتيني انغولا بوتسوانا جنوب افريقيا سيشل زامبيا زيمبابوي ليستوتو مالاوي مدغشقر موريشيوس موزمبيق ناميبيا البانيا أذربيجان تركيا اليونان غيانا الباهامس الحلم يقترب كاس العالم السعودية كاس العالم السعودية كاس العالم السعودية
CLEANED: وناااسه راح تصير اعماركم؟ ستشاهده خبر عظيم جدا وتفاصيل الحلم الذي سيصبح حقيقه باذن الله كاس العالم السعوديه المملكه العربيه السعوديه تحصل علي دعم دوله واتحاد دولي لاستضافه كاس العالم الدول الداعمه للمملكه الاردن قطر البحرين الامارات الكويت سلطنه عمان العراق لبنان فلسطين سوريا اليمن ايران افغانستان باكستان اوزباكستان قيرغيزستان تركمانستان طاجكستان كوريا الجنوبيه كوريا الشماليه اليابان الصين تايبيه الصينيه غوام هونغ كونغ ماكاو منغوليا جزر مارينا الشماليه استراليا بروناي كمبوديا تيمور الشرقيه اندونيسيا لاوس ماليزيا ميانمار الفلبين سنغافوره تايلاند فيتنام بنغلادش بوتان سريلانكا المالديف نيبال تونس مصر المغرب الجزاير ليبيا السودان جيبوتي الصومال جزر القمر موريتانيا بنين بوركينا فاسو توغو الراس الاخضر غينيا ساحل العاج تنزانيا السنغال سيراليون غامبيا غانا غينيا بيساو ليبيريا مالي نيجيريا النيجر افريقيا الوسطي تشاد ساو تاومي وبرينسيب الغابون غينيا الاستواييه الكاميرون الكونغو الكونغو الديموقراطيه اثيوبيا اريتريا اوغندا بوروندي جنوب السودان رواندا زنجبار كينيا اسواتيني انغولا بوتسوانا جنوب افريقيا سيشل زامبيا زيمبابوي ليستوتو مالاوي مدغشقر موريشيوس موزمبيق ناميبيا البانيا اذربيجان تركيا اليونان غيانا الباهامس الحلم يقترب كاس العالم السعوديه كاس العالم السعوديه كاس العالم السعوديه
--------------------------------------------------------------------------------
RAW    : ممثل شهير يكشف مأساة عائلة زوجته غزة عمليهطوفانالاقصي كتايبالقسام طوفانالاقصي طوفانالقدس الاردن الاردن
CLEANED: ممثل شهير يكشف ماساه عايله زوجته غزه عمليهطوفانالاقصي كتايبالقسام طوفانالاقصي طوفانالقدس الاردن الاردن
--------------------------------------------------------------------------------

In [ ]:
Path("/Users/ahmadabotrab/Desktop/arabic_sentiment_classification/data/").mkdir(parents=True, exist_ok=True)

In [37]:
cleaned_df.to_csv("/Users/ahmadabotrab/Desktop/arabic_sentiment_classification/data/cleaned_dataset.csv", index=False)